"""Generate the repetitive mart rollups from a declarative spec.

Each team has a handful of hand-written core facts with real business logic.
Dashboards then want the same numbers cut by day, week and month, and by one
dimension or another. Those cuts are mechanical, so they are generated here, and
the output is committed because dbt reads models from disk.

Change the spec below and rerun::

    uv run python -m platform_ops.simulation.codegen

A test regenerates into memory and compares with the committed files, so a hand
edit to a generated model fails CI rather than drifting from the spec.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

GRAIN_TRUNC: dict[str, str] = {"daily": "day", "weekly": "week", "monthly": "month"}

HEADER = (
    "-- GENERATED by platform_ops.simulation.codegen. Do not edit by hand:\n"
    "-- change the spec in that module and rerun it.\n"
)


@dataclass(frozen=True)
class RollupFamily:
    """One core fact, rolled up by every combination of grain and dimension."""

    team: str
    subject: str
    source: str
    time_column: str
    measures: tuple[tuple[str, str], ...]
    dimensions: tuple[str, ...]
    grains: tuple[str, ...] = ("daily", "weekly", "monthly")

    def model_name(self, grain: str, dimension: str) -> str:
        return f"{self.team}_rpt_{self.subject}_{grain}_by_{dimension}"


ROLLUPS: tuple[RollupFamily, ...] = (
    RollupFamily(
        team="sales",
        subject="orders",
        source="sales_fct_orders",
        time_column="ordered_at",
        measures=(
            ("orders", "count(*)"),
            ("customers", "count(distinct customer_id)"),
            ("net_revenue", "sum(net_amount)"),
            ("avg_order_value", "round(avg(net_amount), 2)"),
        ),
        dimensions=("channel", "country", "status", "discount_code"),
    ),
    RollupFamily(
        team="sales",
        subject="items",
        source="sales_fct_order_items",
        time_column="ordered_at",
        measures=(
            ("units", "sum(quantity)"),
            ("revenue", "sum(line_amount)"),
            ("margin", "sum(line_margin)"),
        ),
        dimensions=("category",),
        grains=("weekly", "monthly"),
    ),
    RollupFamily(
        team="marketing",
        subject="sessions",
        source="marketing_fct_sessions",
        time_column="started_at",
        measures=(
            ("sessions", "count(*)"),
            ("converted_sessions", "count(*) filter (where converted)"),
            ("pageviews", "sum(pageviews)"),
        ),
        dimensions=("device", "traffic_source", "landing_page"),
    ),
    RollupFamily(
        team="marketing",
        subject="attributed_orders",
        source="marketing_fct_attributed_orders",
        time_column="ordered_at",
        measures=(
            ("attributed_orders", "count(*)"),
            ("attributed_revenue", "sum(net_amount)"),
        ),
        dimensions=("attributed_channel",),
    ),
    RollupFamily(
        team="marketing",
        subject="spend",
        source="marketing_fct_daily_spend",
        time_column="activity_date",
        measures=(
            ("spend", "sum(spend)"),
            ("impressions", "sum(impressions)"),
            ("clicks", "sum(clicks)"),
        ),
        dimensions=("channel",),
        grains=("weekly", "monthly"),
    ),
    RollupFamily(
        team="finance",
        subject="revenue",
        source="finance_fct_revenue",
        time_column="recognized_at",
        measures=(
            ("orders", "count(*)"),
            ("recognized_revenue", "sum(recognized_revenue)"),
            ("returned_revenue", "sum(returned_revenue)"),
        ),
        dimensions=("channel", "country", "status"),
    ),
    RollupFamily(
        team="finance",
        subject="margin",
        source="finance_fct_gross_margin",
        time_column="ordered_at",
        measures=(
            ("net_revenue", "sum(net_amount)"),
            ("cost", "sum(cost_amount)"),
            ("margin", "sum(margin_amount)"),
        ),
        dimensions=("channel", "country"),
        grains=("weekly", "monthly"),
    ),
    RollupFamily(
        team="finance",
        subject="refunds",
        source="finance_fct_refunds",
        time_column="ordered_at",
        measures=(
            ("refunds", "count(*)"),
            ("refunded_amount", "sum(refunded_amount)"),
        ),
        dimensions=("channel",),
        grains=("monthly",),
    ),
    RollupFamily(
        team="product",
        subject="tickets",
        source="product_fct_support_tickets",
        time_column="created_at",
        measures=(
            ("tickets", "count(*)"),
            ("breached_tickets", "count(*) filter (where breached_sla)"),
            ("avg_resolution_hours", "round(avg(resolution_hours), 2)"),
        ),
        dimensions=("category", "priority", "ticket_status"),
    ),
    RollupFamily(
        team="product",
        subject="product_sales",
        source="product_fct_product_sales_daily",
        time_column="sale_date",
        measures=(("units", "sum(units)"), ("revenue", "sum(revenue)")),
        dimensions=("category",),
        grains=("weekly", "monthly"),
    ),
    RollupFamily(
        team="product",
        subject="engagement",
        source="product_fct_sessions_engagement",
        time_column="session_date",
        measures=(
            ("sessions", "sum(sessions)"),
            ("converted_sessions", "sum(converted_sessions)"),
        ),
        dimensions=("device",),
        grains=("weekly", "monthly"),
    ),
    RollupFamily(
        team="product",
        subject="funnel",
        source="product_fct_conversion_funnel",
        time_column="activity_date",
        measures=(
            ("sessions", "sum(sessions)"),
            ("engaged_sessions", "sum(engaged_sessions)"),
            ("converted_sessions", "sum(converted_sessions)"),
        ),
        dimensions=("device",),
        grains=("weekly", "monthly"),
    ),
)


def _render_model(family: RollupFamily, grain: str, dimension: str) -> str:
    measures = ",\n".join(f"    {expr} as {alias}" for alias, expr in family.measures)
    return (
        f"{HEADER}"
        f"select\n"
        f"    cast(date_trunc('{GRAIN_TRUNC[grain]}', {family.time_column}) as date)"
        f" as period_start,\n"
        f"    {dimension},\n"
        f"{measures}\n"
        f"from {{{{ ref('{family.source}') }}}}\n"
        f"group by 1, 2\n"
    )


def _render_schema(team: str, names: list[str], dimensions: dict[str, str]) -> str:
    lines = [
        "# GENERATED by platform_ops.simulation.codegen. Do not edit by hand.",
        "version: 2",
        "",
        "models:",
    ]
    for name in names:
        lines += [
            f"  - name: {name}",
            "    data_tests:",
            "      - unique_combination_of_columns:",
            "          arguments:",
            f"            combination_of_columns: [period_start, {dimensions[name]}]",
        ]
    return "\n".join(lines) + "\n"


def render_all() -> dict[str, str]:
    """Every generated file, keyed by its path relative to the dbt project."""
    files: dict[str, str] = {}
    per_team: dict[str, list[str]] = {}
    dimension_of: dict[str, str] = {}
    for family in ROLLUPS:
        for grain in family.grains:
            for dimension in family.dimensions:
                name = family.model_name(grain, dimension)
                if name in dimension_of:
                    raise ValueError(f"duplicate generated model name: {name}")
                path = f"models/marts/{family.team}/generated/{name}.sql"
                files[path] = _render_model(family, grain, dimension)
                per_team.setdefault(family.team, []).append(name)
                dimension_of[name] = dimension
    for team, names in per_team.items():
        path = f"models/marts/{team}/generated/_generated.yml"
        files[path] = _render_schema(team, sorted(names), dimension_of)
    return files


def generated_dirs(dbt_root: Path) -> list[Path]:
    teams = sorted({family.team for family in ROLLUPS})
    return [dbt_root / "models" / "marts" / team / "generated" for team in teams]


def write_all(dbt_root: Path) -> list[Path]:
    """Write every generated file and remove stale ones. Returns what was written."""
    files = render_all()
    wanted = {dbt_root / relative for relative in files}
    for directory in generated_dirs(dbt_root):
        if directory.exists():
            for existing in directory.iterdir():
                if existing.is_file() and existing not in wanted:
                    existing.unlink()
    written: list[Path] = []
    for relative, content in sorted(files.items()):
        target = dbt_root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")
        written.append(target)
    return written


def main() -> None:
    dbt_root = Path(__file__).resolve().parents[3] / "dbt"
    written = write_all(dbt_root)
    models = sum(1 for path in written if path.suffix == ".sql")
    print(f"wrote {models} generated models under {dbt_root}")


if __name__ == "__main__":
    main()
